---
- name: Set Hostname for Ubuntu Machines
  hosts: all
  become: true

  tasks:
    - name: Set hostname
      hostname:
        name: "UD-{{ ansible_default_ipv4.address | regex_replace('\\.', '-') | regex_replace('^.*-(\\d)(\\d)$', '\\1-\\2') }}"
