---
- name: Set Hostname for Ubuntu Machines
  hosts: all
  become: true

  tasks:
    - name: Set hostname
      hostname:
        name: "UD-{{ ansible_default_ipv4.address.split('.')[-2] | last | regex_replace('(\\d)(\\d)$', '\\1-\\2') | regex_replace('^0', '') }}"
