---
- name: Set Hostname for Ubuntu Machines
  hosts: all
  become: true

  tasks:
    - name: Set hostname
      hostname:
        name: "UD-{{ ansible_host | regex_replace('\\.', '-') | regex_replace('^.*-(\d+)$', '\\1') }}"
