---
- name: Set Hostname for Ubuntu Machines
  hosts: all
  become: true

  tasks:
    - name: Get last octet of IP address
      shell: "ip route get 1 | awk '{print $NF}' | cut -d'.' -f4 | tr -d '\n'"
      register: ip_last_octet

    - name: Set hostname
      hostname:
        name: "UD-{{ ip_last_octet.stdout | regex_replace('^0*', '') }}"
