- hosts: all
  become: true
  tasks:
    - name: install qemu
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: yes
- hosts: [pve2]
  become: true
  tasks:
    - name: install nala
      apt:
        name: nala
        state: present
        update_cache: yes